# Generated by Django 5.0.6 on 2024-06-09 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("file_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=1)),
                ("file_path", models.FileField(upload_to="drive/uploads/")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["file_name"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("folder_id", models.AutoField(primary_key=True, serialize=False)),
                ("folder_name", models.CharField(max_length=255)),
                (
                    "folder_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drive.file"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "ordering": ["folder_name"],
            },
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_name"], name="drive_file_file_na_ecbcaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["owner"], name="drive_file_owner_i_1ad568_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["folder_name"], name="drive_folde_folder__936c65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["owner"], name="drive_folde_owner_i_d560e2_idx"),
        ),
    ]
