# Generated by Django 5.0.6 on 2024-06-10 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="folder_content",
        ),
        migrations.AddField(
            model_name="file",
            name="file_parent",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="drive.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="folder_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent Folder",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="drive.folder",
            ),
        ),
    ]
