# Generated by Django 5.0.6 on 2024-06-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_remove_folder_folder_content_file_file_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
