# Generated by Django 5.0.6 on 2024-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0003_alter_file_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="hash",
            field=models.CharField(
                default=0, editable=False, max_length=64, unique=True
            ),
            preserve_default=False,
        ),
    ]
