# Generated by Django 5.0.6 on 2024-06-12 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0004_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
