# Generated by Django 5.0.6 on 2024-06-14 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0005_file_file_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["hash"], name="drive_file_hash_6fb242_idx"),
        ),
    ]
