# Generated by Django 5.0.6 on 2024-06-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0007_folder_hash_folder_drive_folde_hash_edd730_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="folder",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
