# Generated by Django 5.0.6 on 2024-06-26 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0009_folder_created_at_folder_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="folder",
            name="drive_folde_created_7e17da_idx",
        ),
        migrations.RemoveIndex(
            model_name="folder",
            name="drive_folde_updated_4c08ef_idx",
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("folder_name", "folder_parent", "owner")},
        ),
    ]
